package ultratude.com.mzizi.webservice;

public enum APIRequest {

    NOTIFICATION,
    RESULTS_8_4_4,
    RESULTS_2_6_6_3,
    PORTAL_CHAT,
    ALL,
    EVENTS,
    CHATS_GS,
    OPTIONAL_FEE_GS,
    OPTIONAL_FEE,
    TRANSPORT_ROUTE_GS,
    BIO_ACCESS_GS,
    PORTAL_URL_GS,
    SYNC_MY_ACCOUNT,
    STUDENT_INFO,
    NOTIFICATION_READ_TRACKING,
    STUDENT_ATTENDANCE,
    RECENT_TRANSACTION,
    DETAILED_TODO,
    TODO,
    RECENT_RESULTS_8_4_4,
    STUDENT_VISUALIZATION,
    STUDENT_VISUALIZATION_AVERAGE,
    VIDEO_GALLERY,
    PHOTO_GALLERY,
    MZIZI_APP_VERSION,

    TRANSPORT_ROUTES,
    STUDENT_UNITS,
    PORTAL_BOOK_CENTRE,
    PORTAL_BORROWED_BOOKS,
    PORTAL_ORDER_ITEMS,
    PORTAL_SCHOOL_TRIP,
    SEND_TEST_REQUEST,
    PORTAL_SCHOOL_CONTACTS,
    PORTAL_SIBLINGS,
    TRANSACTION,

    TIME_TABLE,


    FCM_MUST,

    REGISTER_FCM_TOKEN

}
